services:
  vardhan_app:
    build: .
    container_name: vardhan_app
    restart: unless-stopped
    environment:
      FLASK_ENV: production
      SECRET_KEY: your-secret-key-here
    volumes:
      - vardhan_data:/app/instance
    networks:
      - planetmilav_wordpress_network

networks:
  planetmilav_wordpress_network:
    external: true

volumes:
  vardhan_data:
