"""Add problem categorization and location fields to service requests

Revision ID: 5894abce7a03
Revises: f1ca8e52b864
Create Date: 2025-02-12 21:39:12.262282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5894abce7a03'
down_revision = 'f1ca8e52b864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('issue_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('issue_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('affected_users', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_working_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('building', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('area_details', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_sr_contract', 'amc_contract', ['contract_id'], ['id'])
        batch_op.create_foreign_key('fk_sr_equipment', 'equipment', ['equipment_id'], ['id'])
        batch_op.drop_column('location_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_details', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint('fk_sr_equipment', type_='foreignkey')
        batch_op.drop_constraint('fk_sr_contract', type_='foreignkey')
        batch_op.drop_column('area_details')
        batch_op.drop_column('room')
        batch_op.drop_column('floor')
        batch_op.drop_column('building')
        batch_op.drop_column('last_working_time')
        batch_op.drop_column('affected_users')
        batch_op.drop_column('issue_frequency')
        batch_op.drop_column('issue_type')
        batch_op.drop_column('equipment_id')
        batch_op.drop_column('contract_id')
        batch_op.drop_column('problem_category')

    # ### end Alembic commands ###
