name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest safety bandit

    - name: Security check - Safety
      run: safety check
      
    - name: Security check - Bandit
      run: bandit -r app/

    - name: Run tests
      run: |
        pytest
        
    - name: Set version tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan planetmilav.com >> ~/.ssh/known_hosts

    - name: Deploy to server
      env:
        SSH_USER: milav
        DEPLOY_PATH: /home/milav/vardhan-flask
      run: |
        # Make deploy.sh executable
        chmod +x deploy.sh
        
        # Copy deploy script to server
        scp deploy.sh $SSH_USER@planetmilav.com:$DEPLOY_PATH/deploy.sh
        
        # Run deploy script
        ssh $SSH_USER@planetmilav.com "cd $DEPLOY_PATH && chmod +x deploy.sh && ./deploy.sh"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
